---
- name: 初始化环境 - 克隆主仓库并安装 pipenv 环境
  hosts: localhost
  gather_facts: yes
  vars:
    repo_url: "https://github.com/wangzitian0/my_finance.git"
    # 你可以根据需要修改目标目录，比如使用绝对路径或相对路径
    repo_dest: "~/my_finance"
    branch: "main"  # 根据你的仓库默认分支名称设置（例如 main 或 master）
  tasks:
    - name: 克隆主仓库（包含子模块）
      git:
        repo: "{{ repo_url }}"
        dest: "{{ repo_dest }}"
        version: "{{ branch }}"
        recursive: yes

    - name: 确保 pipenv 已安装
      pip:
        name: pipenv
        state: present
        executable: pip3

    - name: 执行 pipenv install 安装依赖
      command: pipenv install
      args:
        chdir: "{{ repo_dest }}"
