---
- name: Initial Environment Setup - Bootstrap system, install dependencies, Neo4j, and data repository
  hosts: localhost
  become: yes
  gather_facts: yes
  vars:
    # Neo4j configuration
    neo4j_version: "5.18.0"
    neo4j_tarball: "neo4j-community-{{ neo4j_version }}-unix.tar.gz"
    neo4j_download_url: "https://neo4j.com/artifact.php?name={{ neo4j_tarball }}"
    neo4j_install_dir: "/opt/neo4j"

    # Main repository (my_finance) is assumed to be the current directory.
    branch: "main"

    # Data repository (my_finance_data) configuration:
    # 将数据仓库克隆到与 my_finance 同级目录，即 llm/my_finance_data
    data_repo_url: "git@github.com:wangzitian0/my_finance_data.git"

  tasks:
    - name: Set current directory variable using lookup('env','PWD')
      set_fact:
        current_dir: "{{ lookup('env', 'PWD') }}"
      become: false

    - name: Debug current directory
      debug:
        msg: "Current directory is {{ current_dir }}"
      become: false

    - name: Check if current repository is a git repository
      stat:
        path: "{{ current_dir }}/.git"
      register: main_repo_stat
      become: false

    - name: Fail if current directory is not a git repository
      fail:
        msg: "This playbook must be executed inside the my_finance repository directory. Current directory: {{ current_dir }}"
      when: not main_repo_stat.stat.exists
      become: false

    # -------------------------
    # System and Neo4j setup
    # -------------------------
    - name: Update APT cache and upgrade packages
      apt:
        update_cache: yes
        upgrade: dist

    - name: Install essential system packages (Python3 and pip3)
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - python3
        - python3-pip

    - name: Install OpenJDK 17
      apt:
        name: openjdk-17-jdk
        state: present

    - name: Create Neo4j installation directory
      file:
        path: "{{ neo4j_install_dir }}"
        state: directory

    - name: Download Neo4j tarball
      get_url:
        url: "{{ neo4j_download_url }}"
        dest: "/tmp/{{ neo4j_tarball }}"
        mode: '0644'

    - name: Extract Neo4j tarball to installation directory
      unarchive:
        src: "/tmp/{{ neo4j_tarball }}"
        dest: "{{ neo4j_install_dir }}"
        remote_src: yes
        extra_opts: [--strip-components=1]

    - name: Configure Neo4j to listen on 0.0.0.0
      lineinfile:
        path: "{{ neo4j_install_dir }}/conf/neo4j.conf"
        regexp: '^#?dbms\.default_listen_address='
        line: 'dbms.default_listen_address=0.0.0.0'
        state: present

    - name: Start Neo4j service
      command: "{{ neo4j_install_dir }}/bin/neo4j start"
      register: neo4j_start
      failed_when: (neo4j_start.rc != 0) and ("Neo4j is already running" not in neo4j_start.stderr)

    - name: Check Neo4j service status
      command: "{{ neo4j_install_dir }}/bin/neo4j status"
      register: neo4j_status
      changed_when: false

    - name: Display Neo4j service status
      debug:
        var: neo4j_status.stdout_lines

    # -------------------------
    # Data repository handling
    # -------------------------
    # 目标：将数据仓库克隆到 llm/my_finance_data，并在 my_finance 中建立符号链接 data 指向 ../my_finance_data
    - name: Set sibling directory variable for data repository
      set_fact:
        data_repo_dest: "{{ current_dir | dirname }}/my_finance_data"
      become: false

    - name: Check if sibling directory my_finance_data exists
      stat:
        path: "{{ data_repo_dest }}"
      register: sibling_stat
      become: false

    - name: Clone data repository (my_finance_data) using SSH
      git:
        repo: "{{ data_repo_url }}"
        dest: "{{ data_repo_dest }}"
        version: "{{ branch }}"
      become: false
      when: not sibling_stat.stat.exists

    - name: Check if local "data" directory exists in my_finance
      stat:
        path: "{{ current_dir }}/data"
      register: local_data_stat
      become: false

    - name: Remove existing "data" directory in my_finance (if any)
      file:
        path: "{{ current_dir }}/data"
        state: absent
      become: false
      when: local_data_stat.stat.exists

    - name: Create symlink "data" in my_finance pointing to sibling my_finance_data
      file:
        src: "../my_finance_data"
        dest: "{{ current_dir }}/data"
        state: link
      become: false

    # -------------------------
    # Install pipenv dependencies
    # -------------------------
    - name: Install pipenv dependencies (creates virtual environment)
      command: pipenv install
      args:
        chdir: "{{ current_dir }}"
      become: false

    - name: Final message
      debug:
        msg: "Initial environment setup complete. Verify Neo4j at http://localhost:7474."
      become: false
