---
- name: Update code for my_finance and its submodules; update pipenv environment for my_finance
  hosts: localhost
  gather_facts: yes
  vars:
    # Assume current directory is my_finance
    finance_repo: "."
    neo4j_install_dir: "/opt/neo4j"

  tasks:
    - name: Pull latest changes for my_finance (main repository)
      command: git pull
      args:
        chdir: "{{ finance_repo }}"
      become: no

    - name: Update submodules for my_finance (if any)
      command: git submodule update --remote --merge
      args:
        chdir: "{{ finance_repo }}"
      become: no

    - name: Update pipenv dependencies for my_finance (refresh environment)
      command: pipenv install
      args:
        chdir: "{{ finance_repo }}"
      become: no

    # -------------------------
    # Check Neo4j service status
    # -------------------------
    - name: Check Neo4j service status
      command: "{{ neo4j_install_dir }}/bin/neo4j status"
      register: neo4j_status
      changed_when: false

    - name: Display Neo4j service status
      debug:
        var: neo4j_status.stdout_lines

    - name: Restart Neo4j if it is not running
      command: "{{ neo4j_install_dir }}/bin/neo4j restart"
      register: neo4j_restart
      failed_when: (neo4j_status.rc != 0) and ("Neo4j is already running" in neo4j_status.stderr)
      changed_when: true

    - name: Check Neo4j service status again after restart
      command: "{{ neo4j_install_dir }}/bin/neo4j status"
      register: neo4j_status_after_restart
      changed_when: false

    - name: Display Neo4j service status after restart
      debug:
        var: neo4j_status_after_restart.stdout_lines

    - name: Fail if Neo4j is still not running after restart
      fail:
        msg: "Neo4j failed to start after attempting a restart."
      when: neo4j_status_after_restart.rc != 0

    - name: Final message
      debug:
        msg: "Repositories updated and my_finance environment refreshed. Ready to pull new data!"
