---
- name: Update code for my_finance and its submodules; update pipenv environment for my_finance
  hosts: localhost
  gather_facts: yes
  vars:
    # Assume current directory is my_finance
    finance_repo: "."
  tasks:
    - name: Pull latest changes for my_finance (main repository)
      command: git pull
      args:
        chdir: "{{ finance_repo }}"
      become: no

    - name: Update submodules for my_finance (if any)
      command: git submodule update --remote --merge
      args:
        chdir: "{{ finance_repo }}"
      become: no

    - name: Update pipenv dependencies for my_finance (refresh environment)
      command: pipenv install
      args:
        chdir: "{{ finance_repo }}"
      become: no

    - name: Final message
      debug:
        msg: "Repositories updated and my_finance environment refreshed. Ready to pull new data!"
